/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_taskbar_TaskbarJFrameGrouper */

#ifndef _Included_com_example_taskbar_TaskbarJFrameGrouper
#define _Included_com_example_taskbar_TaskbarJFrameGrouper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_taskbar_TaskbarJFrameGrouper_ROWS
#define com_example_taskbar_TaskbarJFrameGrouper_ROWS 3L
#undef com_example_taskbar_TaskbarJFrameGrouper_COLUMNS
#define com_example_taskbar_TaskbarJFrameGrouper_COLUMNS 4L
#undef com_example_taskbar_TaskbarJFrameGrouper_GAP
#define com_example_taskbar_TaskbarJFrameGrouper_GAP 50L
/*
 * Class:     com_example_taskbar_TaskbarJFrameGrouper
 * Method:    assignWindowToGroup
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_taskbar_TaskbarJFrameGrouper_assignWindowToGroup
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
